In [2]:
import torch

In [3]:
randint = torch.randint(-100,100,(6,))
randint

tensor([-92, -78,  24,  82,  24, -26])

In [4]:
tensor = torch.tensor([[0,1.2,4],[5.67,2,5],[2,5,8]])
tensor

tensor([[0.0000, 1.2000, 4.0000],
        [5.6700, 2.0000, 5.0000],
        [2.0000, 5.0000, 8.0000]])

In [5]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
ones = torch.ones(2,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
input = torch.empty(2,3)
input

tensor([[1.4878e-03, 1.5512e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [8]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [9]:
linspace =  torch.linspace(3,10,steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [10]:
logspace = torch.logspace(start=-10,end=10,steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [11]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [12]:
a = torch.empty((2,3),dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[4755514464176,             0,             0],
        [            0,             0,             0]])

## Section 2 - Using GPU-->  Above ones using CPU

In [13]:
import torch
import numpy as np
import time
device ='cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [14]:
start_time =  time.time()
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time 
print(f"{elapsed_time:.8f}")

0.00093961


In [15]:
import time
import numpy as np
import torch

# Matrix size
N = 1000

# Generate random matrices
A = np.random.rand(N, N).astype(np.float32)
B = np.random.rand(N, N).astype(np.float32)

# CPU matrix multiplication using NumPy
start_time_cpu = time.time()
C_cpu = np.dot(A, B)
end_time_cpu = time.time()

cpu_time = end_time_cpu - start_time_cpu
print(f"CPU time (NumPy): {cpu_time:.4f} seconds")

# GPU matrix multiplication using PyTorch
A_torch = torch.tensor(A, dtype=torch.float32).cuda()
B_torch = torch.tensor(B, dtype=torch.float32).cuda()

start_time_gpu = time.time()
C_gpu = torch.matmul(A_torch, B_torch)
torch.cuda.synchronize()  # Ensure all operations are finished
end_time_gpu = time.time()

gpu_time = end_time_gpu - start_time_gpu
print(f"GPU time (PyTorch): {gpu_time:.4f} seconds")


CPU time (NumPy): 0.0280 seconds
GPU time (PyTorch): 0.3785 seconds


# More torch examples

In [21]:
# Define a probability tensor
probabilities = torch.tensor([0.1,0.9])
# 10% -> 0, 90% -> 1, each probability points to the index of the probability in the tensor

#Draw 5 samples from the multinomial distribution
samples =  torch.multinomial(probabilities,num_samples=10,replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [22]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor,torch.tensor([5,6])),dim=0) #dim=0 means concatenation is happening along the first dimension (rows in 1D, or vertically in 2D/3D).
out

tensor([1, 2, 3, 4, 5, 6])

In [24]:
out = torch.tril(torch.ones(5,5)) # tril =>  triangle upper
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [26]:
out = torch.triu(torch.ones(5,5)) # true => triangle upper
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [34]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [35]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [36]:
input = torch.zeros(2,3,4)
out = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])